# Generated by Django 5.2.4 on 2026-05-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('video', models.FileField(upload_to='videos/')),
                ('tmdb_id', models.PositiveIntegerField(blank=True, help_text='TMDB movie ID — save with this set to auto-fill all metadata', null=True, unique=True)),
                ('genre', models.CharField(blank=True, default='', max_length=200)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, default='', max_length=20)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('poster_remote_url', models.URLField(blank=True, default='', help_text='Auto-filled from TMDB. Used when no local poster uploaded.', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
