# Generated by Django 5.2.4 on 2026-05-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='_tmdb_id_fetched',
            field=models.PositiveIntegerField(blank=True, help_text='Internal: tracks which tmdb_id was last fetched.', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
