# Generated by Django 5.2.4 on 2026-05-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie__tmdb_id_fetched_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, default='', help_text='Auto-filled YouTube trailer from TMDB.', max_length=500),
        ),
    ]
