# Generated by Django 5.2.4 on 2026-05-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_trailer_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, default='', help_text='Auto-filled YouTube embed URL from TMDB.', max_length=500),
        ),
    ]
